import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import MainNav from '@/components/MainNav';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ticket Application',
  description: 'Generated by Tomoya',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
          <nav className={'flex flex-row justify-center border-b py-2'}>
            <div className={'max-w-6xl w-full'}>
              <MainNav />
            </div>
          </nav>
          <main className={'flex flex-col items-center py-2'}>
            <div className={'max-w-6xl w-full'}>{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
